// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalOuvidoria.Infra.Data.Context;

#nullable disable

namespace PortalOuvidoria.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250210125331_TabelaChamados")]
    partial class TabelaChamados
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("PortalOuvidoria.Domain.Entities.Chamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ComentarioFinalizado")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdSituacao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenAcompanhamento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UTC_DataAnalise")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UTC_DataComentario")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UTC_DataEvidencia")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UTC_DataFinalizado")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UTC_DataRegistro")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UTC_DataRegistro_10Dias")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UTC_DataRegistro_25Dias")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Chamados");
                });
#pragma warning restore 612, 618
        }
    }
}
